### PR TITLE
Updated to be more dynamic. Added support for Eucalyptus 4.1.

### PR DESCRIPTION
**Pull request by quadespresso**
TODO: Provide per-schema breakdown of database utilization (ref: creation of database_sizes.txt).

### CODE REVIEW

**Comment by hspencer77** [comment]
Hey @quadespresso , thanks for the pull request.  One thing here, I see the following:

```
+        if (self.isInstalled("eucalyptus-cloud") and
+            ((self.isInstalled("postgresql91") and self.isInstalled("postgresql91-server")) or
+           (self.isInstalled("postgresql91") and self.isInstalled("postgresql91-server")))
+           ):
```
Eucalyptus 4.1 depends upon Postgres 9.2:
```
# rpm -qR eucalyptus-cloud
/usr/bin/perl
bc
euca2ools >= 2.0
eucalyptus = 4.1.0-0.0.23044.8.el6
eucalyptus-common-java(x86-64) = 4.1.0-0.0.23044.8.el6
eucanetd = 4.1.0-0.0.23044.8.el6
lvm2
openssl(x86-64) >= 1.0.1e-16
perl(Getopt::Long)
perl(Getopt::Long)
perl(strict)
postgresql91
postgresql91-server
postgresql92
postgresql92-server
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(VersionedDependencies) <= 3.0.3-1
rpmlib(PayloadIsXz) <= 5.2-1
```
I didn't see anything in the pull request that uses postgres 9.1 for Eucalyptus 4.0.x and postgres 9.2 for Eucalyptus 4.1.  Would you mind updating the pull request to reflect that dependency?  Thanks again for this.

**Comment by hspencer77** [comment]
Additionally, @quadespresso would you mind using [flake8](http://flake8.readthedocs.org/en/2.2.3/) to make sure your code follows PEP8 standards.  I have started doing this for this 0.1.7 to help clean up the code.  After you install flake8 using pip, just run it as follows:
```
# flake8 eucalyptus-sosreport-plugins
```
Thanks again for this.

**Comment by quadespresso** [comment]
Heh, I'd set up the logic for checking for the postgresql92* packages, I'd just neglected to make the final edits. :-) That's fixed now, and I've cleaned things up to be PEP8 compliant.

**Comment by hspencer77** [comment]
This is a pull request for https://github.com/eucalyptus/eucalyptus-sosreport-plugins/issues/69

**Pull request merged**
